title: Searching for Boba
author: Mark Bauer, Nathan Williamson, Chidi Ezeolu
repository:
  url: https://github.com/datalifenyc/boba-nyc
html:
  use_repository_button: true
  use_issues_button: true
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js