title: Searching for Boba
author: Mark Bauer, Chidi Ezeolu, Ho Hsieh, Nathan Williamson
copyright: "2022"
logo: "bubble-tea-title-img.jpg"
repository:
  url: https://github.com/datalifenyc/boba-nyc
  path_to_book: teabook
  branch: master
html:
  favicon: favicon.ico
  use_repository_button: true
  use_issues_button: true
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/datalifenyc/boba-nyc/HEAD"
  colab_url: "https://colab.research.google.com"
